import {direction,spot,fmt} from './engine.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,label,disabled=false)=>`<button type="button" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
export function quickGame(s,doc,{crew=false}={}){
 const pending=s.flags.some(f=>f.outcome==='pending'),ordinary=s.currentPlay&&s.playType==='scrimmage'&&!s.currentPlay.possessionChanges?.length;
 return `<section class="card quick-game" aria-label="Quick game controls"><header class="card-head"><div><h2>${crew?'Crew essentials':'Quick play tracker'}</h2><p>${s.down} &amp; ${Math.abs(s.lineToGain-s.position)} · ${esc(s.possession)} ${direction(s)>0?'→':'←'} · ${spot(s.position)}</p></div>${button('undo','Undo',!doc.undo.length)}</header><p class="muted">${crew?'Mark only what needs attention. Detailed play logging is optional in Scorekeeper.':'Record the snap, then the result. Down, distance and possession update automatically. Clock is a reference—not the official scoreboard.'}</p><div class="action-grid">${button('quick-mark','MARK')}${button('quick-no-call','NO-CALL')}${button('quick-review','REVIEW')}${!crew?button('flag','Penalty'):''}</div>${crew?'':`<hr>${pending?'<p class="warning">Pending penalty: record the result if needed, then confirm enforcement before another snap.</p>':''}${!s.currentPlay?button(s.playType==='kickoff'?'kick-touch':'snap',s.playType==='kickoff'?'Legal kick touch':'Start play / snap',pending):ordinary?`<div class="action-grid">${button('quick-incomplete','Incomplete — save')}${button('whistle','Whistle / stop')}</div><form id="quick-result-form" data-revision="${doc.revision}" class="form-grid"><label>Result<select name="result"><option>Run</option><option>Complete</option><option>Out of bounds</option><option>Turnover</option></select></label><div class="action-grid gain-presets wide">${[-5,-1,1,3,5,7,10,15].map(g=>`<button type="button" data-gain-preset="${g}">${g>0?'+'+g:g}</button>`).join('')}</div><label class="wide">Net gain or loss (yards)<input name="gain" type="number" inputmode="numeric" step="1" min="-99" max="99" value="0" required></label><button class="primary wide">Save result → next down</button></form><p class="muted">Tap a preset or type the yards gained (or lost, as a negative number) — the system moves the ball and sets the next down and distance. Goal-line plays, kicks, returns and scoring need advanced controls below.</p>`:'<p class="info">Kick, try, or live possession change: confirm the result in advanced controls below.</p>'}<div class="action-grid">${s.activeStop?button('end-stoppage','End stoppage'):button('quick-timeout','Timeout — possessing team',!!s.currentPlay)}${button('ready','Ready for play',!!s.currentPlay||pending)}</div>`}<p class="info" role="status">${esc(s.notice)}</p><p class="muted">Markers save in the game ledger. Video markers are also requested when a recording is active; verify available footage in Saved video.</p></section>`;
}
export function trackingSummary(s,doc){
 const plays=s.plays.filter(p=>!p.noPlay),markers=s.markers||[];
 return {recordedPlays:plays.length,completions:plays.filter(p=>p.result==='Complete').length,incompletions:plays.filter(p=>p.result==='Incomplete').length,markers:markers.map(m=>({...m})),scoringPlays:plays.filter(p=>['Touchdown','Field goal','Safety','Try good (1)','Try good (2)'].includes(p.result)).map(p=>({id:p.id,quarter:p.quarter,result:p.result,possession:p.possession})),correctionActions:doc.audit.filter(a=>['UNDO','REDO','SET_GAME','CORRECT_CLOCK','SCORE','TIMEOUTS'].includes(a.type)).length,warnings:[...(s.currentPlay?['A started play has no saved result.']:[]),...(s.flags.some(f=>f.outcome==='pending')?['Penalty decisions remain pending.']:[]),...(s.activeStop?['A stoppage is still open; its final duration is not included.']:[]),'Missing/unlogged plays cannot be counted automatically. These are recorded-play totals, not verified full-game statistics.','Marker status is not reconciled with the separate video evaluator ledger; no review-completion rate is inferred.']};
}
export function trackingReport(s,doc){
 const r=trackingSummary(s,doc);
 return `<section class="card"><h2>Tracking &amp; crew review</h2><p>${r.recordedPlays} recorded plays · ${r.completions} recorded completions · ${r.incompletions} incompletions · ${r.correctionActions} correction/undo actions</p><h3>Plays to review</h3>${r.markers.length?r.markers.map(m=>`<p>${esc(m.kind)} · Q${m.quarter} ${fmt(m.game)} · ${m.playId?'play '+m.playId:'between plays'} · ${spot(m.position)} · ${esc(m.id)}</p>`).join(''):'<p>No review markers recorded.</p>'}<h3>Recorded scoring plays</h3>${r.scoringPlays.map(p=>`<p>Q${p.quarter} · Play ${p.id} · ${esc(p.result)} · possession at start: ${esc(p.possession)}</p>`).join('')||'<p>No scoring plays logged. Score corrections are separate.</p>'}<h3>Data quality</h3><ul>${r.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></section>`;
}
